# steps:
#   - name: 'gcr.io/cloud-builders/git'
#     args: ['clone', 'https://github.com/manipatnam1203/test-looker.git', '/workspace/repo']
    
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args: ['-m', 'rsync', '-r', '/workspace/repo/dags', 'gs://gcs-looker/dags']
steps:
# Step 1: Clone the GitHub repository
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/manipatnam1203/test-looker.git']
# Step 2: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/looker-test:latest', '.']
# Step 3: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/looker-test:latest']
# Step 4: Pull Docker image from Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/looker-test:latest']
# Step 5: Extract files from Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['create', '--name', 'artifact-container', 'gcr.io/$PROJECT_ID/looker-test:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['cp', 'artifact-container:/app/dags', '.']

# Step 6: Upload files to Google Cloud Storage
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', '-m','rsync', '-r', './dags', 'gs://gcs-looker/dags']
#  args: ['gsutil', 'cp', '-r', './files-to-transfer', 'gs://your-cloud-storage-bucket/']


options:
  logging: CLOUD_LOGGING_ONLY