steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/manipatnam1203/test-looker']
    
  
  # Store the commit hash for reference
  - name: 'alpine'
    entrypoint: '/bin/sh'
    args: ['-c', 'git rev-parse HEAD > /workspace/last_commit.txt']

  # List the changed files in the last commit
  - name: 'alpine'
    entrypoint: '/bin/sh'
    args: ['-c', 'git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD) > /workspace/changed_files.txt']

  # Filter out changes specific to the "dags" folder
  - name: 'alpine'
    entrypoint: '/bin/sh'
    args: ['-c', 'grep "dags/" /workspace/changed_files.txt > /workspace/changed_dags.txt']
  
  # Build Docker image with all files
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-artifact:latest', '.']

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-artifact:latest']

  # Sync only the changed files in 'dags' folder to Google Cloud Storage
  - name: 'google/cloud-sdk'
    entrypoint: '/bin/bash'
    args:
    - '-c'
    - |
      while read -r file; do
        gsutil cp $file gs://gcs-looker/dags/$file
      done < /workspace/changed_dags.txt

  #           gsutil cp "src/$file" "gs://gcs-looker/dags/$file"


options:
  logging: CLOUD_LOGGING_ONLY

# adding cache