
steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/manipatnam1203/test-looker.git', '/workspace/repo']
    
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '/workspace/repo/dags', 'gs://test-cloudbuild-24/dags']


options:
  logging: CLOUD_LOGGING_ONLY