steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/manipatnam1203/test-looker']
    
  # Identify changed files
  - name: 'alpine/git'
    args: ['log', '--name-only', '--pretty="format:"', '-1']
    entrypoint: '/bin/sh'
    args: ['-c', 'git log --name-only --pretty="format:" -1 > changed_files.txt']

  # Build the Docker image with all files
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-artifact:latest', '.']
  
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-artifact:latest']
  
  # Sync only changed files to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        while read -r file; do
          if [[ -f "dags/$file" ]]; then
            gsutil cp "dags/$file" "gs://gcs-looker/dags/$file"
          fi
        done < changed_files.txt
  #           gsutil cp "src/$file" "gs://gcs-looker/dags/$file"


options:
  logging: CLOUD_LOGGING_ONLY

# adding cache