
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/manipatnam1203/test-looker.git']

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Capture changed SQL files in the last commit
    changed_files=$(git show --name-only | grep 'bigquery/')

    # If there are changes, proceed with deployment
    if [ -n "$changed_files" ]; then
      for sql_file in $changed_files; do
      #  echo $sql_file >> files.txt
        bq query \
          --project_id=${_PROJECT_ID} \
          --use_legacy_sql=false \
          < $sql_file
      done
    else
      echo "No changes to SQL files in the last commit."
    fi
    #cat files.txt
  
options:
  logging: CLOUD_LOGGING_ONLY