steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - 'https://github.com/manipatnam1203/test-looker.git'
  - --branch=dev

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Get a list of all the files that have changed in the last commit.
    CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

    # Filter the list of files to only include SQL files.
    SQL_FILES=$(grep "\.sql$" <<< "${CHANGED_FILES}")

    # Execute each of the SQL files in the list.
    for SQL_FILE in ${SQL_FILES}; do
      bq query \
        --project_id=${_PROJECT_ID} \
        --use_legacy_sql=false \
        < "${SQL_FILE}"
    done