steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Capture changed SQL files in the last commit
    previous_commit=$(git log --format="%H" -n 1 HEAD^)
    changed_files=$(git diff --name-only $previous_commit HEAD -- 'bigquery/**/*.sql')

    # If there are changes, proceed with deployment
    if [ -n "$changed_files" ]; then
      for sql_file in $changed_files; do
        bq query \
          --project_id=${_PROJECT_ID} \
          --use_legacy_sql=false \
          < $sql_file
      done
    else
      echo "No changes to SQL files in the last commit."
    fi

options:
  logging: CLOUD_LOGGING_ONLY