substitutions:
  CHANGED_FILES: $(git diff --name-only HEAD^ HEAD)

steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - 'https://github.com/manipatnam1203/test-looker.git'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Execute each of the SQL files in the list.
    for SQL_FILE in "${CHANGED_FILES}"; do
      bq query \
        --project_id=${_PROJECT_ID} \
        --use_legacy_sql=false \
        < "${SQL_FILE}"
    done
  
  options:
  logging: CLOUD_LOGGING_ONLY