steps:
# Deploy the stored procedures in the BigQuery
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    bq query \
      --project_id=$_PROJECT_ID \
      --use_legacy_sql=false \
      < $_SQL_FILE

options:
  logging: CLOUD_LOGGING_ONLY